ebusiness/ebusiness/urls.py
import os

from django.conf.urls import static, url
from django.contrib import admin
from django.urls import path
from django.views.static import serve

from ebusiness import settings
from ebusiness.settings import BASE_DIR
from goods import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),

    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

    # url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # 用户注册
    url(r'^register/$', views.register),
    # 主页
    url(r'^$', views.index),
    url(r'^index/$', views.index),
    url(r'^login_action/$', views.login_action),
    # 用户登出
    url(r'^logout/$', views.logout),
    # 用户信息显示
    url(r'^user_info/$', views.user_info),
    # 修改用户密码
    url(r'^change_password/$', views.change_password),
    # 商品信息显示
    url(r'^goods_view/$', views.goods_view),
    # 商品信息的模糊查询
    url(r'^search_name/$', views.search_name),
    # 查看商品详情
    url(r'^view_goods/(?P<good_id>[0-9]+)/$', views.view_goods),
    # 添加购物车
    url(r'^add_chart/(?P<good_id>[0-9]+)/(?P<sign>[0-9]+)/$', views.add_chart),
    # 查看购物车中的商品
    url(r'^view_chart/$', views.view_chart),
    # 修改购物车中的商品数量
    url(r'^update_chart/(?P<good_id>[0-9]+)/$', views.update_chart),
    # 删除购物车中的某种商品
    url(r'^remove_chart/(?P<good_id>[0-9]+)/$', views.remove_chart),
    # 删除购物车内所有的商品
    url(r'^remove_chart_all/$', views.remove_chart_all),

    # 送货地址的添加与显示
    url(r'^add_address/(?P<sign>[0-9]+)/$', views.add_address),
    url(r'^view_address/$', views.view_address),
    # 送货地址的修改
    url(r'^update_address/(?P<address_id>[0-9]+)/(?P<sign>[0-9]+)/$', views.update_address),
    # 收货地址的删除
    url(r'^delete_address/(?P<address_id>[0-9]+)/(?P<sign>[0-9]+)/$', views.delete_address),

    # 总订单的生成和显示
    url(r'^create_order/$', views.create_order),
    url(r'^view_order/(?P<orders_id>[0-9]+)/$', views.view_order),
    # 查看所有订单
    url(r'^view_all_order/$', views.view_all_order),
    # url(r'^static/(?P.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
]




# handler403 = views.permission_denied
# handler404 = views.page_not_found
# handler500 = views.page_error

ebusiness/goods/models.py
from django.db import models

# Create your models here.

# 用户
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.username

# 商品
class Goods(models.Model):
    name = models.CharField(max_length=100)     # 商品名称
    price = models.FloatField()         # 单价
    picture = models.FileField(upload_to='./static/')   # 图片
    desc = models.TextField()   # 描述

    def __str__(self):
        return self.name

# 收货地址
class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)  # 关联用户id
    address = models.CharField(max_length=50)  # 地址
    phone = models.CharField(max_length=15)  # 电话

    def __str__(self):
        return self.address


# 总订单
class Orders(models.Model):
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING)  # 关联送货地址id
    create_time = models.DateTimeField(auto_now=True)  # 创建时间
    status = models.BooleanField()  # 订单状态

    def __str__(self):
        return self.create_time


# 一个订单
class Order(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.DO_NOTHING)  # 关联总订单id
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)  # 关联用户id
    goods = models.ForeignKey(Goods, on_delete=models.DO_NOTHING)  # 关联商品id
    count = models.IntegerField()  # 数量

ebusiness/goods/forms.py
from django import forms

# 定义注册表单模型
class UserForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=100)
    password = forms.CharField(label='密码', widget=forms.PasswordInput())
    email = forms.EmailField(label='电子邮件')

class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=100)
    password = forms.CharField(label='密码', widget=forms.PasswordInput())

class AddressForm(forms.Form):
    address = forms.CharField(label='地址', max_length=100)
    phone = forms.CharField(label='电话', max_length=15)

ebusiness/goods/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, get_object_or_404, redirect

from goods.forms import UserForm, LoginForm, AddressForm

# Create your views here.
# 用户注册
from goods.models import User, Address, Goods, Orders, Order
from goods.object import Order_list, Orders_list
from goods.util import Util


def register(request):
    if request.method == 'POST':    # 判断表单是否提交状态
        uf = UserForm(request.POST) # 判断表单变量
        if uf.is_valid():           # 判断表单数据是否正确
            # 获取表单
            username = (request.POST.get('username')).strip()   # 获取用户名信息
            password = (request.POST.get('password')).strip()   # 获取密码信息
            email = (request.POST.get('email')).strip()         # 获取Email信息

            # 查找数据库中存在相同的用户名
            user_list = User.objects.filter(username=username)
            if user_list:
                # 如果存在,就报'用户名已经存在！', 并且回到注册页面
                return render_to_response('register.html', {'uf':uf, "error":"用户名已经存在！"})
            else:
                # 否则将表单写入数据库
                user = User()
                user.username = username
                user.password = password
                user.email = email
                user.save()
                # 返回登录页面
                uf = LoginForm()
                return render_to_response('index.html', {'uf':uf})
    else:   # 如果不是表单提交状态, 就显示表单信息
        uf = UserForm()
    return render_to_response('register.html', {'uf':uf})

# 显示首页
def index(request):
    uf = LoginForm()
    return render_to_response('index.html', {'uf':uf})

def logout(request):
    '''
    用户登出
    :param request:
    :return:
    '''
    response = HttpResponseRedirect('/index/')
    del request.session['username']
    return response

# 用户登录
def login_action(request):
    if request.method == 'POST':
        uf = LoginForm(request.POST)
        if uf.is_valid():
            # 寻找名为username和password的POST参数,而且如果参数没有提交,就返回一个空的字符串
            username = (request.POST.get('username')).strip()
            password = (request.POST.get('password')).strip()
            # 判断输入数据是否为空
            if username == '' or password =='':
                return render_to_response(request, "index.html", {'uf':uf, "error":"用户名和密码不能为空！"})
            else:
                # 判断用户名和密码是否正确
                user = User.objects.filter(username=username, password=password)
                if user:
                    # 登录成功后跳转查看商品信息
                    response = HttpResponseRedirect('/goods_view/')
                    request.session['username'] = username  # 将session信息写到服务器
                    return response
                else:
                    return render(request, "index.html", {'uf':uf, "error":'用户名或者密码错误！'})
        else:
            uf = LoginForm()
        return render_to_response('index.html', {'uf':uf})

def user_info(request):
    # 检查用户是否登录
    util = Util()
    username = util.check_user(request)
    # 如果没有登录,就跳转到首页
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'uf':uf, "error":"请登录后再进入！"})
    else:
        # cont为当前购物车商品的数量
        count = util.cookies_count(request)
        # 获取登录用户信息
        user_list = get_object_or_404(User, username=username)
        # 获取登录用户收货地址的所有信息
        address_list = Address.objects.filter(user_id=user_list.id)
        return render(request, 'view_user.html', {"user":username,"user_info":user_list, "address":address_list, "count":count})

def change_password(request):
    '''
    修改用户密码
    :param request:
    :return:
    '''
    util = Util()
    username = util.check_user(request)
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'uf':uf, "error":"请登录后再进入"})
    else:
        count = util.cookies_count(request)
    # 获得当前登录用户的用户信息
    user_info = get_object_or_404(User, username=username)
    # 如果是提交表单, 就获取表单信息, 并且进行表单信息验证
    if request.method == 'POST':
        # 获取旧密码
        oldpassword = (request.POST.get("oldpassword", "")).strip()
        # 获取新密码
        newpassword = (request.POST.get("newpassword", "")).strip()
        # 获取新密码的确认密码
        checkpassword = (request.POST.get("checkpassword", "")).strip()
        # 如果旧密码不正确, 就报错误信息, 不允许修改
        if oldpassword != user_info.password:
            return render(request, "change_password.html", {'user':username, 'error':'原密码不正确, 请确定后重新输入！', 'count':count})
        # 如果旧密码与新密码相同,就报错误信息, 不允许修改
        elif oldpassword == newpassword:
            return render(request, "change_password.html", {'user':username, 'error':'新密码与旧密码相同,请重新输入！', 'count':count})
        # 如果新密码与确认密码不同,报错
        elif newpassword != checkpassword:
            return render(request, 'change_password.html', {'user':username, 'error':'两次输入的密码不同！', 'count':count})
        else:
            # 否则修改成功
            User.objects.filter(username=username).update(password=newpassword)
            return render(request, "change_password.html", {'user':username, 'error':'密码修改成功！请牢记密码！', 'count':count})
    else:
        return render(request, "change_password.html", {'user':username, 'count':count})


# 商品管理部分
def goods_view(request):
    '''
    查看商品信息
    :param request:
    :return:
    '''
    util = Util()
    username = util.check_user(request)
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'uf':uf, "error":"请登录后再进入！"})
    else:
        # 获得所有商品信息
        good_list = Goods.objects.all()
        # 获得购物车物品数量
        count = util.cookies_count(request)

        # 翻页操作
        paginator = Paginator(good_list, 5)
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            contacts = paginator.page(1)
        return render(request, "goods_view.html", {"user":username, "goodss":contacts, "count":count})

def search_name(request):
    '''
    商品搜索
    :param request:
    :return:
    '''
    util = Util()
    username = util.check_user(request)
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'uf':uf, "error":"请登录后再进入！"})
    else:
        count = util.cookies_count(request)
        # 获取查询数据
        search_name = (request.POST.get("good", "")).strip()
        # 通过objects.filter()方法进行模糊匹配查询, 查询结果放入变量good_list
        good_list = Goods.objects.filter(name__icontains=search_name)

        # 对查询结果进行分页显示
        paginator = Paginator(good_list, 5)
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # 如果页号不是一个整数, 就返回第一页
            contacts = paginator.page(1)
        except EmptyPage:
            # 如果页号查出范围(如9999), 就返回结果的最后一页
            contacts = paginator.page(paginator.num_pages)
        return render(request, "goods_view.html", {"user":username, "goodss":contacts, "count":count})

def view_goods(request, good_id):
    '''
    查看商品详情
    :param request:
    :return:
    '''
    util = Util()
    username = util.check_user(request)
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'uf':uf, "error":"请登录后再进入！"})
    else:
        count = util.cookies_count(request)
        good = get_object_or_404(Goods, id=good_id)
        return render(request, 'good_details.html', {'user':username, 'good':good, 'count':count})

# 购物车部分
def add_chart(request, good_id, sign):
    '''
    加入购物车
    :param request:
    :param good_id:
    :param sign:
    :return:
    '''
    util = Util()
    username = util.check_user(request)
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'error':"请登录后再进入！"})
    else:
        # 获得商品详情
        good = get_object_or_404(Goods, id=good_id)
        # 如果sign==1, 则返回商品列表页面
        if sign == "1":
            response = HttpResponseRedirect('/goods_view/')
        # 否则返回商品详情页面
        else:
            response = HttpResponseRedirect('/view_goods/' + good_id)
        # 把当前商品添加进购物车, 参数为商品id, 值为购买商品的数量, 默认为1, 有效时间是一年
        response.set_cookie(str(good.id), 1, 60 * 60 * 24 * 365)
        return response

def view_chart(request):
    '''
    查看购物车中的商品
    :param request:
    :return:
    '''
    util = Util()
    username = util.check_user(request)
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'uf':uf, 'error':'请登录后再进入！'})
    else:
        # 购物车中的商品个数
        count = util.cookies_count(request)
        # 返回所有的cookie内容
        my_chart_list = util.add_chart(request)
        return render(request, "view_chart.html", {"user":username, "goodss":my_chart_list, "count":count})

def update_chart(request, good_id):
    '''
    修改购物车中的商品数量
    :param request:
    :param good_id:
    :return:
    '''
    util = Util()
    username = util.check_user(request)
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'uf':uf, 'error':'请登录后再进入！'})
    else:
        # 获取编号为good_id的商品
        good = get_object_or_404(Goods, id=good_id)
        # 获取修改的数量
        count = (request.POST.get("count" + good_id, "")).strip()
        # 如果数量值<=0, 就报出错信息
        if int(count) <= 0 :
            # 获得购物车列表信息
            my_chart_list = util.add_chart(request)
            # 返回错误信息
            return render(request, "view_chart.html", {'user':username, 'goodss':my_chart_list, 'error':'个数不能少于或等于0！'})
        else:
            # 否则修改商品数量
            response = HttpResponseRedirect('/view_chart/')
            response.set_cookie(str(good_id), count, 60 * 60 * 24 * 365)
            return response

def remove_chart(request, good_id):
    '''
    把购物车中的商品移除购物车
    :param request:
    :param good_id:
    :return:
    '''
    util = Util()
    username = util.check_user(request)
    if username == "":
        uf = LoginForm()
        return render(request, "index.html", {'uf':uf, 'error':'请登录后再操作！'})

ebusiness/templates/add_address.html
{%load staticfiles%}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>添加地址</title>
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet"-->
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet"-->
	<link href="{%static 'css/my.css'%}" rel="stylesheet">
</head>

<body>

  <div class="container">
    <form class="form-signin" method="post" enctype="multipart/form-data">
      <h2 class="form-signin-heading">添加地址</h2>
	  {% csrf_token %}
      {{uf.as_p}}
        <p style="color:red">{{error}}</p> <br>
      <button class="btn btn-lg btn-primary btn-block" type="submit">提交</button><br>
    </form>

  </div> <!-- /container -->

</body>
</html>

ebusiness/templates/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
      <meta name="description" content="">
      <meta name="author" content="">

      <title>买买买！</title>

      <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet"-->
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet"-->
  </head>

  <body role="document">
<!-- 导航栏 -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/goods_view/">电子商务系统</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/goods_view/">商品列表</a></li>
			<li class="active"><a href="/view_all_order/">查看所有订单</a></li>
  {% block content %}


  {% endblock %}
    <div class="container theme-showcase" role="main">

        <div class="page-header">
        </div>
        <footer class="footer">
          <p>&copy; Company 2018,作者：Hamdi</p>
        </footer>

    </div> <!-- /container -->

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
  <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  </body>

</html>

ebusiness/templates/change_password.html
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>

      <div class="row">
        <div class="col-md-6">
          <form action="/change_password/" method="post" enctype="multipart/form-data">
		  {% csrf_token %}
            <p style="color:red">{{error}}</p> <br>
            旧密码：<input name="oldpassword" type="password" required><br>
            新密码：<input name="newpassword" type="password" required><br>
            确认密码：<input name="checkpassword" type="password" required><br>
            <input type="submit" value="修改">
          </form>
        </div>

      </div>

{% endblock %}

ebusiness/templates/good_details.html
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">
      <!--商品详情-->
      <div class="row" style="margin-top:30px">
        <div class="col-lg-6">
          <div class="input-group">
		  单价：￥{{good.price}}元 <a href="/add_chart/{{good.id}}/2/">放入购物车</a><br>
		  <img src="/{{good.picture}}"><br>
		  {{good.desc}}
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
      </div><!-- /.row -->

    </div> <!-- /container   glyphicon glyphicon-phone border-style:none; -->

{% endblock %}

ebusiness/templates/goods_view.html
{% extends "base.html" %}
{% block content %}
            <li class="active"><a href="/view_chart/">查看购物车<font color="#FF0000">{{ count }}</font></a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">

      <!--商品表单-->
      <div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form" method="post" action="/search_name/">
            <div class="form-group">
			{% csrf_token %}
              <input name="good" type="text" placeholder="名称" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">搜索</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>

      <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
                <th>名称</th>
                <th>价钱</th>
				<th>查看详情</th>
                <th>放入购物车</th>
              </tr>
            </thead>
            <tbody>
              {% for goods in goodss %}
                <tr>
                  <td>{{ goods.id }}</td>
                  <td>{{ goods.name }}</td>
                  <td>￥{{ goods.price }}</td>
                  <td><a href="/view_goods/{{goods.id}}/">查看</a></td>
                  <td><a href="/add_chart/{{goods.id}}/1/">放入</a></td>
                </tr>
             {% endfor %}
            </tbody>
          </table>
        </div>

      </div>
 <!-- 列表分页器 -->
    <div class="pagination">
      <span class="step-links">
        {% if goodss.has_previous %}
          <a href="?page={{ goodss.previous_page_number }}">上一页</a>
        {% endif %}
          <span class="current">
            Page {{ goodss.number }} of {{ goodss.paginator.num_pages }}.
          </span>
        {% if goodss.has_next %}
          <a href="?page={{ goodss.next_page_number }}">下一页</a>
        {% endif %}
      </span>
    </div>
{% endblock %}

ebusiness/templates/index.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>电子商务系统-登录</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
	<link href="{%static 'css/my.css'%}" rel="stylesheet">

  </head>

  <body>

    <div class="container">
      <form class="form-signin" method="post" action="/login_action/" enctype="multipart/form-data">
	  {% csrf_token %}
        <h2 class="form-signin-heading">我买网系统-----登录</h2>
        {{uf.as_p}}
          <p style="color:red">{{error}}</p> <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button><br>
		<a href="\register\">注册</a>
      </form>

    </div> <!-- /container -->
  </body>

</html>

ebusiness/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>电子商务系统-注册</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet"-->
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet"-->
	<link href="{%static 'css/my.css'%}" rel="stylesheet">

  </head>

  <body>

    <div class="container">
      <form class="form-signin" method="post" enctype="multipart/form-data">
        <h2 class="form-signin-heading">电子商务系统-注册</h2>
		<!--{% csrf_token %}-->
        {{uf.as_p}}
          <p style="color:red">{{error}}</p> <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button><br>
		<a href="/index/">登录</a>
      </form>

    </div> <!-- /container -->

  </body>

</html>

ebusiness/templates/update_address.html
{%load staticfiles%}
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>修改地址</title>
    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/signin.css'%}" rel="stylesheet"-->
    <!-- Custom styles for this template -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet"-->
	<link href="{%static 'css/my.css'%}" rel="stylesheet">
</head>

<body>

  <div class="container">
    <form class="form-signin" method="post" enctype="multipart/form-data">
      <h2 class="form-signin-heading">修改地址</h2>
	  {% csrf_token %}
      <p><label for="id_address">地址:</label> <input type="text"  value="{{address.address}}" name="address" id="id_address" size="20" maxlength="100" required /></p>
	  <p><label for="id_phone">电话:</label> <input type="text" value="{{address.phone}}" name="phone" id="id_phone" size="20" maxlength="15" required /></p>
		<p style="color:red">{{error}}</p> <br>
      <button class="btn btn-lg btn-primary btn-block" type="submit">修改</button><br>
    </form>

  </div> <!-- /container -->

</body>
</html>

ebusiness/templates/view_chart.html
{% extends "base.html" %}
{% block content %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <li><a href="/user_info/">{{user}}</a></li>
           <li><a href="/logout/">退出</a></li>
         </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	<div class="page-header">
        <div id="navbar" class="navbar-collapse collapse">
        </div><!--/.navbar-collapse -->
      </div>
    <div class="container theme-showcase" role="main">
	<font color="#FF0000">{{error}}</font>
      <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>编号</th>
                <th>名称</th>
                <th>价钱</th>
				        <th>个数</th>
                <th>移除</th>
              </tr>
            </thead>
            <tbody>
			  {% for key in goodss %}
                <tr>
                  <td><a href="/view_goods/{{key.id}}/">{{key.id}}</a></td>
                  <td>{{key.name}}</td>
                  <td>￥{{key.price}}</td>
                  <td><form action="/update_chart/{{key.id}}/" method="post">
				  {% csrf_token %}
				  <input type="number" value="{{key.count}}" style="width:30px;" name="count{{key.id}}" class="vIntegerField" id="id_count" required />
				  <input type="submit" value="修改" /></form></td>
                  <td><a href="/remove_chart/{{key.id}}/">移除</a></td>
                </tr>
             {% endfor %}
            </tbody>
          </table>
		  <form method="get" action="/remove_chart_all/">
		  {% csrf_token %}
		  <input type="submit" value="清除所有">
		  </form>
		  <form method="get" action="/view_address/">
		  {% csrf_token %}
		  <input type="submit" value="生成订单">
		  </form>
        </div>

      </div>
{% endblock %}